version: '3'
services:
  hanami:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        RUBY_VERSION: '2.7.6'
    command: 'bundle exec hanami server --host 0.0.0.0 -p 2300'
    ports:
      - 2300:2300
    volumes:
      - .:/app:cached
    stdin_open: true
    tty: true
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'app_development'
      MYSQL_USER: 'app_user'
      MYSQL_PASSWORD: 'app_password'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'